### ISSUE TITLE
Stretchy Shoe effect not working

### ISSUE THREAD

**Issue by dioncullum29** [ItsEasyActually/SA1_Chars#32]
Sonic's feet no longer stretch like the original effect from the JP version. I don't know if I am missing something or what, but it is driving me crazy.

**Comment by ItsEasyActually** [comment]
The shoes stretch, but only the normal ones. I did add new models for the LS Shoes so they also stretch as well since the original only had the effect on the normal shoes. This is a configuration option though, and I don't believe those are enabled by default.

I think what you're actually talking about is the blurring/after images effect since you specifically mentioned the JP version. The shoes stretch in all versions, but the JP version did the after-images. All of that is covered in this mod: https://github.com/michael-fadely/sadx-onion-blur

**Comment by TehJellyLord** [comment]
Ah no I meant the shoe stretch, I had it all mixed up. How do I enable it for the LS shoes as well?

**Comment by dioncullum29** [comment]
Ah okay, I had it mixed up. I was talking about the stretch effect, and I never actually knew that effect didn't apply to the LS shoes. Thanks!
